### PR TITLE
Update deploy/delete/dependencies

### PR DESCRIPTION
**Pull request by dsensibaugh**
Updates to:

taskcat deploy - separated command into run/list
taskcat delete - now does multithreading
mock dependency - updated to unittest.mock
docker integration tests

### CODE REVIEW

**Comment by andrew-glenn** [comment]
@dsensibaugh I'm finding that `taskcat list` doesn't behave the same way as `taskcat deploy list`. Is this intentional?

**Comment by andrew-glenn** [comment]
If it's an easy lift, I think it'd be great to solve for `taskcat list` too.

**Comment by jarrettandrulis** [comment]
While we’re at it, should we just go ahead and rename ‘package’? Something like ‘project’, ‘production’, or similar?

**Comment by andrew-glenn** [comment]
@dsensibaugh When y'all are at a good spot, please rebase from `main` as I've fixed the recent linting issues. I'd like to get passing travis tests before I run end to end.

**Comment by jarrettandrulis** [comment]
Merged in now, let me check our additions  to see how well they work with the new changes to main

**Review by andrew-glenn — APPROVED** [review]

**Pull request merged**
