### PR TITLE
Fixing schema generator to support 3.8;

### PR DESCRIPTION
**Pull request by andrew-glenn**
There's a bug in the schema generator where py3.8 isn't supported. I added in support and it now raises an exception if an unsupport version of python is used. 

## Overview

Brief description of what this PR does, and why it is needed (use case)?

## Testing/Steps taken to ensure quality

How did you validate the changes in this PR?

### Notes

Optional. Caveats, Alternatives, Other relevant information.

## Testing Instructions

 How to test this PR Start after checking out this branch (bulleted)
 * Include test case, and expected output

### CODE REVIEW

**Review by jaymccon — DISMISSED** [review]

**Comment by andrew-glenn** [comment]
Superceded by #669

**Pull request closed without merging**
