### PR TITLE
Add Python 3.9 support

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by andrew-glenn** [comment]
@gliptak - Thanks for this PR! For housekeeping purposes, I'm flipping this to draft while you iterate on the Travis testing part. Mark it as ready once that's ironed out! 👍

**Comment by gliptak** [comment]
```mypy``` might not fully support ```3.9``

https://travis-ci.org/github/aws-quickstart/taskcat/jobs/749308055

```
taskcat/_cli_modules/upload.py:36: error: syntax error in type comment
Found 1 error in 1 file (checked 37 source files)
```
https://github.com/python/mypy/issues/9761

**Comment by hauntsaninja** [comment]
You're using a pretty old version of mypy, if you switch to a recent version that error will go away :-)

**Comment by gliptak** [comment]
@hauntsaninja same error even after moving to latest `pre-commit`

https://travis-ci.org/github/aws-quickstart/taskcat/jobs/749501718

**Comment by gliptak** [comment]
https://github.com/pre-commit/pre-commit.com/pull/453/files

**Comment by gliptak** [comment]
```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 2
taskcat/testing/_abstract_test.py:67: error: syntax error in type comment
taskcat/testing/_abstract_test.py:78: error: syntax error in type comment
Found 2 errors in 1 file (checked 44 source files)
```

**Pull request closed without merging**
