### PR TITLE
Adding role_arn to Project,Test config schema, plus tests. Closes #323

### LINKED ISSUE #323: Feature Request: Optional Stack Role ARN Parameter
Something that would be extremely helpful was if taskcat supported passing a stack role to be used when creating test stacks. 

When deploying CloudFormation stacks in a CodePipeline, the stack role is a required parameter. This can lead to some interesting issues where taskcat can pass its tests, but the deployment can fail due to subtle differences in the roles between the two. Additionally, it would be nice to limit the permissions given to the CodeBuild project running taskcat, but allow it to pass a role to CloudFormation for the test stacks.

### PR DESCRIPTION
**Pull request by andrew-glenn**
## Overview

This adds `role_arn` to project and test-level config schema. I've added tests, but local env issues are preventing a full test suite. Need to iron that out before ready for review.

### CODE REVIEW

**Comment by andrew-glenn** [comment]
Will rebase and handle once other PRs are merged so effort duplication doesn't occur.

**Comment by jaymccon** [comment]
how does this work with multiple accounts in `auth` ?

**Comment by andrew-glenn** [comment]
> how does this work with multiple accounts in `auth` ?

Good catch. Flipping back to draft while I figure out how to handle this in multi-auth scenarios.

**Comment by diranged** [comment]
Please ship this!

**Comment by jaymccon** [comment]
> > how does this work with multiple accounts in `auth` ?
> 
> Good catch. Flipping back to draft while I figure out how to handle this in multi-auth scenarios.

why not just use role name, and build the arn? Then the expectation in a multi-account scenario is that the role is pre-created in all accounts.

A side note, but I believe stack roles are not broadly used or recommended because of [this](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-servicerole.html) limitation:

> Other users that have permissions to perform operations on this stack will be able to use this role, even if they don't have permission to pass it. If the role includes permissions that the user shouldn't have, you can unintentionally escalate a user's permissions. Ensure that the role grants least privilege.

**Comment by zetas** [comment]
I finally ran up against a scenario where my AWS user does not have the same privileges as my cloudformation execution role so I can't use taskcat to launch stacks. It will always fail as my user, but launching via the GUI and using the execution role succeeds. Thank you so much @andrew-glenn for workin on this. I can't wait for its release and the full inclusion of taskcat into our dev pipeline.

**Comment by andrew-glenn** [comment]
@jaymccon - I originally flipped this back to Draft to investigate your suggestions. Now that I'm actually reviewing your suggestions, I'd prefer to leave this as-is. Providing an explicit ARN answers all questions around intent. Supplying a RoleARN answers all of the questions around intent.

While I have confidence around our ability to stick together an ARN, I believe _less is more_ is appropriate in this case. Should there be any permissions issues, the end-user will be able to more easily identify the source and 'assumed' profile. With a profile name, it becomes more opaque.

**Comment by andrew-glenn** [comment]
After discussing further out of band, I'm realizing role_name is a better pattern since it allows us to better control the user experience and mitigate sharp edges that a regional-specific ARN would generate when testing across multiple regions. 


This means I need to backtrack a little and add a utility function to generate the ARN from the role name

**Pull request merged**
