### PR TITLE
Add initial Dockerfile

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

## Overview

```
docker run taskcat:latest             
 _            _             _   
| |_ __ _ ___| | _____ __ _| |_ 
| __/ _` / __| |/ / __/ _` | __|
| || (_| \__ \   < (_| (_| | |_ 
 \__\__,_|___/_|\_\___\__,_|\__|
                                


version 0.9.13
usage: taskcat [args] <command> [args] [subcommand] [args]
```

### CODE REVIEW

**Comment by gliptak** [comment]
@andrew-glenn ```Docker``` allows running on ```Windows``` (without ```WSL```) and removes the need to ```pip install``` on other OSs

As for credentials, would this below work?

```
docker run -e AWS_PROFILE=$AWS_PROFILE taskcat:latest
``` 

I'm looking at pre-commit

**Comment by gliptak** [comment]
@andrew-glenn build is green

**Comment by andrew-glenn** [comment]
Generally yes. We also use the AWS credentials, so copying in ~/.aws has been done in the past. However I'm not seeing evidence that's done today, so my comment may have been in error.

In summary: we should chat about it internally before we ask you to change your PR further. Thanks for the contribution! It looks great. I'm just hesitant to merge _right now_ because I'm not convinced we (as a team) have a consensus quite yet.

**Comment by gliptak** [comment]
@andrew-glenn thank you for working this. I understand the need to arrive to consensus. After merge, I will submit docs PR.

PS wrapping various tooling with ```Docker``` (and avoiding dependency installs, package installs, distro specific compiles) is a trend I'm seeing with more and more (open source) projects

**Pull request closed without merging**
