### PR TITLE
Add functions to collect stack resources

### PR DESCRIPTION
**Pull request by sshvans**
Add functions to collect stack resources

### CODE REVIEW

**Comment by sshvans** [comment]
@avattathil Merge when you get a chance. Should be straight forward.

**Comment by santiagocardenas** [comment]
Have we thought about the multi-account and boto session management?

**Comment by sshvans** [comment]
@santiagocardenas Yes. We have it in our backlog.

**Comment by avattathil** [comment]
For external don't think we need it since only one account is involved

On Feb 23, 2017 3:38 PM, "Santiago Cardenas" <notifications@github.com>
wrote:

Have we thought about the multi-account and boto session management?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/aws-quickstart/taskcat/pull/4#issuecomment-282157484>,
or mute the thread

**Pull request merged**
