### PR TITLE
Template url

### PR DESCRIPTION
**Pull request by gargana**
## Overview

Added try except logic to not exit taskcat because of a bad URL

## Testing/Steps taken to ensure quality

Ran the pre-commit hooks

### Notes

None

## Testing Instructions

How to test this PR Start after checking out this branch (bulleted)
Run this version of taskcat against templates with a badly formed TemplateURL
eg:
{'Fn::Sub': ['https://${S3Bucket}.${S3Region}.{AWS::URLSuffix}/${KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template', {'S3Region': {'Fn::Sub': 's3.${AWS::Region}'}, 'S3Bucket': {'Fn::If': ['UsingDefaultBucket', {'Fn::Sub': '${BucketName}-${AWS::Region}'}, {'Ref': 'BucketName'}]}}]}

Note that {AWS::URLSuffix} should be ${AWS::URLSuffix}

### CODE REVIEW

**Comment by avattathil** [comment]
**I think we should explicitly enable this feature till its baked!** 
Can we add a key to the global cfg or a flag or something that invokes this code path. 
`s3_path_validation:  true `
Due to the nature this pre-process some values will only be validated at run-time. If those run-time evals are not handled, we will hit an exception, these conditions looks like they are caught and handled - but I would feel better if we mark this feature _alpha_ and have the ability enable on a per project bases, once its stable we are revisit

**Comment by andrew-glenn** [comment]
One other thing I noticed, but isn't in this PR because it's already in the feature branch:

- I'd like to see the generate_test_from_template script accommodate beyond your desktop. I see hard-coded values in there.

**Comment by gargana** [comment]
> **I think we should explicitly enable this feature till its baked!**
> Can we add a key to the global cfg or a flag or something that invokes this code path.
> `s3_path_validation: true `
> Due to the nature this pre-process some values will only be validated at run-time. If those run-time evals are not handled, we will hit an exception, these conditions looks like they are caught and handled - but I would feel better if we mark this feature _alpha_ and have the ability enable on a per project bases, once its stable we are revisit

This should now mimic the existing code as well as handling additional cases.
Features still required:
- Changes to recurse children only on a per test basis.
  - taskcat test run "linting" to be done on a per test case basis for evaluation of Runtime info.
  - Evaluation of Conditions
    - This will allow for accurate evaluations of *"Fn::If"*
  - Handling of Pseudo Parameters
    - *AWS::AccountId*
    - *AWS::URLSuffix*
    - *AWS::Region*
  - Refactor the naming of the various substitutions and separating the substitution logic for easier maintenace
- Negative tests

**Comment by gargana** [comment]
> One other thing I noticed, but isn't in this PR because it's already in the feature branch:
> 
> * I'd like to see the generate_test_from_template script accommodate beyond your desktop. I see hard-coded values in there.

Noted I have made a change to accommodate that

**Comment by jaymccon** [comment]
@gargana are all the conversations on this resolved ? can we re-review/merge ?

**Comment by gargana** [comment]
Added the e2e test which produces a broken path that can't evaluate and returns a blank string instead.

**Comment by jaymccon** [comment]
for some reason e2e bot is not picking up this pr, investigating.

**Comment by jaymccon** [comment]
ok, I think I'm going to put this back onto the feature branch, but note that we can't do e2e tests then, let's run them locally for now, once we've got this merged into the feature branch we can open another pr to merge into master (and run e2e on that).

**Pull request merged**
